In [1]:
import numpy as np

In [2]:
import numpy as np

data=np.load('./data/mnist-data.npz')

data

NpzFile './data/mnist-data.npz' with keys: training_data, training_labels, test_data

In [3]:
data['training_labels']

array([3, 7, 1, ..., 3, 7, 1], shape=(60000,), dtype=uint8)

In [4]:
data=np.load('./data/spam-data.npz')

data

NpzFile './data/spam-data.npz' with keys: training_data, training_labels, test_data

In [5]:
data['training_labels']

array([1, 1, 1, ..., 0, 0, 0], shape=(4171,))

In [6]:
data['training_data']

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], shape=(4171, 32))